server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: academic-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/students/**

        - id: academic-service-classroom
          uri: http://localhost:8081
          predicates:
            - Path=/api/classroom/**

        - id: payment-service-tuitions
          uri: http://localhost:8082
          predicates:
            - Path=/api/tuitions/**

        - id: payment-service-payments
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**